### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by Justyyy** [imqurex/Valorant-Triggerbot#3]
It's staying at this black bar, what should I do?

https://i.ibb.co/2KPH93w/pre.png

**Comment by imqurex** [comment]
Nothing. Just leave it open in the background. Its just there for showing how fast the bot reacted (in ms) and also it's open because the script has to run. This should be fine and the bot should work.

**Comment by Justyyy** [comment]
Yeah but the problem is nothing showing in the CMD in ms or smth as reaction time etc.

Add me on discord please, I can screenshare Corei#8134
