### ISSUE TITLE
config.txt

### ISSUE THREAD

**Issue by OwOwennn** [imqurex/Valorant-Triggerbot#5]
ok i have no idea if im just being dumb but were is config.txt / how should it be formated because it just says missing / invalid config.txt

**Comment by imqurex** [comment]
The **_.txt_** file should be created in the folder where the 2 python files are located in. The path where you run the files. I don't reccomend copying the text and putting it in visual studio as an example. Just download the **_.zip_**, extract it and run everything in that path.

Also, is something blocking the process or did you rename anything?

**Comment by imqurex** [comment]
For faster replies add me on Discord. 

!    𝖖𝖚𝖗𝖊𝖝ツ#7848

**Comment by yazsd** [comment]
discord its wrong

**Comment by imqurex** [comment]
!    𝖖𝖚𝖗𝖊𝖝ツ#7848 
 ^ 
  |
With 4 spaces between the "!" and "q".
Github for some reason makes 1 space out of it.
